server:
  port: 8086

spring:
  application:
    name: Payment-Microservice

  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:payment-postgres}:${PAYMENT_DB_PORT:5432}/${PAYMENT_DB_NAME:payment_db}
    username: ${PAYMENT_DB_USER:payment_user}
    password: ${PAYMENT_DB_PASSWORD:payment_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}