server:
  port: 8083

spring:
  application:
    name: Inventory-Microservice

  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:inventory-postgres}:${INVENTORY_DB_PORT:5432}/${INVENTORY_DB_NAME:inventory_db}
    username: ${INVENTORY_DB_USER:inventory_user}
    password: ${INVENTORY_DB_PASSWORD:inventory_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}