CREATE TABLE recommendations (
                                 recommendation_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                                 user_id BIGINT NOT NULL,

                                 active BOOLEAN NOT NULL DEFAULT TRUE,

                                 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 created_by BIGINT,

                                 updated_by BIGINT,

                                 CONSTRAINT pk_recommendations
                                     PRIMARY KEY (recommendation_id),

                                 CONSTRAINT uk_recommendations_user_id
                                     UNIQUE (user_id)
);


CREATE TABLE recommendation_products (
                                         recommendation_id BIGINT NOT NULL,

                                         product_id BIGINT NOT NULL,

                                         CONSTRAINT fk_recommendation_products_recommendation
                                             FOREIGN KEY (recommendation_id)
                                                 REFERENCES recommendations(recommendation_id)
                                                 ON DELETE CASCADE
);