server:
  port: 8087

spring:
  application:
    name: Notification-Microservice

  datasource:
    url: jdbc:postgresql://${NOTIFICATION_DB_HOST:notification-postgres}:${NOTIFICATION_DB_PORT:5432}/${NOTIFICATION_DB_NAME:notification_db}
    username: ${NOTIFICATION_DB_USER:notification_user}
    password: ${NOTIFICATION_DB_PASSWORD:notification_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}