CREATE TABLE payments (
                          payment_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                          order_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,

                          payment_method VARCHAR(50) NOT NULL,
                          payment_status VARCHAR(50) NOT NULL,

                          amount NUMERIC(12, 2) NOT NULL,
                          currency VARCHAR(3) NOT NULL DEFAULT 'INR',

                          transaction_id VARCHAR(255),
                          gateway_reference_id VARCHAR(255),

                          refund_id VARCHAR(255),
                          refund_amount NUMERIC(12, 2) DEFAULT 0,

                          payment_date TIMESTAMP(6),
                          refund_date TIMESTAMP(6),

                          failure_reason VARCHAR(500),

                          created_at TIMESTAMP(6) NOT NULL,
                          updated_at TIMESTAMP(6) NOT NULL,

                          CONSTRAINT pk_payments
                              PRIMARY KEY (payment_id),

                          CONSTRAINT uk_payments_order_id
                              UNIQUE (order_id),

                          CONSTRAINT uk_payments_transaction_id
                              UNIQUE (transaction_id),

                          CONSTRAINT uk_payments_gateway_reference_id
                              UNIQUE (gateway_reference_id)
);