CREATE TABLE orders (
                        order_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                        order_number VARCHAR(255) NOT NULL,
                        user_id BIGINT NOT NULL,
                        address_id BIGINT NOT NULL,
                        payment_id BIGINT,

                        status VARCHAR(50) NOT NULL,

                        subtotal NUMERIC(19, 2) NOT NULL,
                        discount NUMERIC(19, 2) NOT NULL,
                        shipping_charge NUMERIC(19, 2) NOT NULL,
                        tax NUMERIC(19, 2) NOT NULL,
                        total_amount NUMERIC(19, 2) NOT NULL,

                        payment_method VARCHAR(50) NOT NULL,

                        estimated_delivery_date DATE,
                        placed_at TIMESTAMP(6),

                        created_at TIMESTAMP(6) NOT NULL,
                        updated_at TIMESTAMP(6) NOT NULL,

                        CONSTRAINT pk_orders
                            PRIMARY KEY (order_id),

                        CONSTRAINT uk_orders_order_number
                            UNIQUE (order_number)
);


CREATE TABLE order_items (
                             order_item_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                             order_id BIGINT NOT NULL,

                             product_id BIGINT NOT NULL,
                             seller_id BIGINT NOT NULL,

                             product_name_snapshot VARCHAR(255) NOT NULL,
                             sku_snapshot VARCHAR(255) NOT NULL,
                             main_image_url_snapshot VARCHAR(255),

                             price_snapshot NUMERIC(19, 2) NOT NULL,
                             discount_snapshot NUMERIC(19, 2) NOT NULL,
                             special_price_snapshot NUMERIC(19, 2) NOT NULL,

                             quantity INTEGER NOT NULL,
                             line_total NUMERIC(19, 2) NOT NULL,

                             created_at TIMESTAMP(6) NOT NULL,
                             updated_at TIMESTAMP(6) NOT NULL,

                             CONSTRAINT pk_order_items
                                 PRIMARY KEY (order_item_id),

                             CONSTRAINT fk_order_items_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(order_id)
);


CREATE INDEX idx_orders_user_id
    ON orders(user_id);


CREATE INDEX idx_orders_status
    ON orders(status);


CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);