server:
  port: 8082

spring:
  application:
    name: Catalog-Microservice

  data:
    mongodb:
      uri: mongodb://${CATALOG_MONGO_USERNAME}:${CATALOG_MONGO_PASSWORD}@${CATALOG_MONGO_HOST:catalog-mongodb}:${CATALOG_MONGO_PORT:27017}/${CATALOG_MONGO_DATABASE}?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}