server:
  port: 8084

spring:
  application:
    name: Cart-Microservice

  data:
    redis:
      host: ${CART_REDIS_HOST:cart-redis}
      port: ${CART_REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}