CREATE TABLE notifications (
                               notification_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                               user_id BIGINT NOT NULL,

                               notification_type VARCHAR(50) NOT NULL,

                               recipient VARCHAR(255) NOT NULL,

                               subject VARCHAR(255) NOT NULL,

                               message TEXT,

                               status VARCHAR(50) NOT NULL,

                               reference_type VARCHAR(50) NOT NULL,

                               reference_id BIGINT NOT NULL,

                               active BOOLEAN DEFAULT TRUE,

                               created_by BIGINT,

                               updated_by BIGINT,

                               created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

                               updated_at TIMESTAMP(6),

                               CONSTRAINT pk_notifications
                                   PRIMARY KEY (notification_id)
);


CREATE TABLE notification_preferences (
                                          preference_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                                          user_id BIGINT NOT NULL,

                                          email_enabled BOOLEAN DEFAULT TRUE,

                                          sms_enabled BOOLEAN DEFAULT TRUE,

                                          push_enabled BOOLEAN DEFAULT TRUE,

                                          active BOOLEAN DEFAULT TRUE,

                                          created_by BIGINT,

                                          updated_by BIGINT,

                                          CONSTRAINT pk_notification_preferences
                                              PRIMARY KEY (preference_id),

                                          CONSTRAINT uk_notification_preferences_user_id
                                              UNIQUE (user_id)
);