CREATE TABLE inventory (
                           inventory_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           product_id BIGINT NOT NULL,
                           sku VARCHAR(100) NOT NULL,
                           available_quantity INTEGER NOT NULL DEFAULT 0,
                           reserved_quantity INTEGER NOT NULL DEFAULT 0,
                           sold_quantity INTEGER NOT NULL DEFAULT 0,
                           minimum_stock_level INTEGER NOT NULL DEFAULT 10,
                           active BOOLEAN NOT NULL DEFAULT TRUE,
                           created_by BIGINT NOT NULL,
                           updated_by BIGINT NOT NULL,
                           created_at TIMESTAMP(6) NOT NULL,
                           updated_at TIMESTAMP(6) NOT NULL,

                           CONSTRAINT pk_inventory
                               PRIMARY KEY (inventory_id),

                           CONSTRAINT uk_inventory_product_id
                               UNIQUE (product_id),

                           CONSTRAINT uk_inventory_sku
                               UNIQUE (sku)
);